// backend/src/patterns.rs
// Six vulnerability category detectors.
// Pure deterministic static analysis — no AI, no network, no heuristics.
// Each finding includes a complete description and recommendation written here,
// not generated by AI. AI later adds semantic *context* for marked findings.

use crate::{
    ast_visitor::{get_line_snippet, ProjectVisitor},
    types::{Category, Finding, InputFile, Severity},
};

pub fn detect_all(visitor: &ProjectVisitor, files: &[InputFile]) -> Vec<Finding> {
    let mut findings = vec![];
    let mut id = 0u32;
    let mut next_id = move || { id += 1; format!("CP-{id:03}") };

    // Core 6 detectors
    findings.extend(check_account_validation(visitor, files, &mut next_id));
    findings.extend(check_arithmetic(visitor, files, &mut next_id));
    findings.extend(check_signer_authority(visitor, files, &mut next_id));
    findings.extend(check_pda_seeds(visitor, files, &mut next_id));
    findings.extend(check_reentrancy(visitor, files, &mut next_id));
    findings.extend(check_access_control(visitor, files, &mut next_id));

    // Advanced v4.1 detectors
    findings.extend(crate::detectors::detect_advanced(visitor, files, &mut next_id));

    // Real-world exploit patterns (from Sherlock, NomosLabs)
    findings.extend(crate::exploits::detect_exploits(&visitor, files, &mut next_id));

    // Professional audit patterns (from Ackee, Neodyme, DeFimSOL)
    findings.extend(crate::pro_audits::detect_pro_audits(&visitor, files, &mut next_id));

    findings
}

//   1. ACCOUNT VALIDATION                           ─

fn check_account_validation(
    visitor: &ProjectVisitor,
    files: &[InputFile],
    next_id: &mut impl FnMut() -> String,
) -> Vec<Finding> {
    let mut out = vec![];

    for s in &visitor.account_structs {
        for f in &s.fields {
            let is_raw = f.field_type.contains("AccountInfo")
                && !f.field_type.contains("Program <")
                && !f.field_type.contains("Sysvar <");
            let is_authority = matches!(
                f.name.as_str(),
                "authority" | "admin" | "owner" | "payer" | "operator" | "maker" | "creator"
            );

            // Raw AccountInfo for authority without any guards
            if is_raw && is_authority && !f.is_signer {
                let (snippet, line) = visitor.snippet_for_pattern(
                    &s.file, &format!("pub {}", f.name), 3,
                );
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::High,
                    category: Category::AccountValidation,
                    title: format!("Authority `{}` typed as AccountInfo — no ownership verification", f.name),
                    file: s.file.clone(), line: Some(line),
                    function: s.name.clone(),
                    snippet,
                    description: format!(
                        "`{}` in struct `{}` is `AccountInfo<'info>` which performs zero runtime \
                        checks. An attacker can pass any arbitrary account as `{}` — it will be \
                        accepted without verifying ownership, program ID, or even that it signed \
                        the transaction. This is the root cause of many Solana exploits.",
                        f.name, s.name, f.name
                    ),
                    recommendation: format!(
                        "Replace `AccountInfo<'info>` with `Signer<'info>` if `{}` must sign. \
                        Anchor's `Signer<>` type automatically verifies the account signed the \
                        current transaction. Also add `has_one = {}` on any state account that \
                        stores this authority's pubkey.",
                        f.name, f.name
                    ),
                    anchor_fix: format!("pub {}: Signer<'info>", f.name),
                    cwe: "CWE-284".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }

            // init_if_needed without reinitialization guard
            let has_iim = f.constraints.iter().any(|c| c.contains("init_if_needed"));
            if has_iim && !f.has_constraint && !f.has_has_one {
                let (snippet, line) = visitor.snippet_for_pattern(&s.file, "init_if_needed", 4);
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::High,
                    category: Category::AccountValidation,
                    title: format!("`init_if_needed` on `{}` without reinitialization guard", f.name),
                    file: s.file.clone(), line: Some(line),
                    function: s.name.clone(),
                    snippet,
                    description: format!(
                        "`init_if_needed` on `{}` silently accepts pre-existing accounts. Without \
                        a guard constraint, an attacker can pre-create an account with forged data \
                        and pass it here — Anchor skips init but accepts the account, allowing \
                        reinitialization with attacker-controlled state.",
                        f.name
                    ),
                    recommendation: "Add `constraint = account.data_is_empty() @ ErrorCode::AlreadyInitialized` \
                        to reject pre-existing accounts, or replace `init_if_needed` with `init` if \
                        the account should only ever be created once.".into(),
                    anchor_fix: format!(
                        "#[account(init_if_needed, constraint = {}.data_is_empty())]", f.name
                    ),
                    cwe: "CWE-665".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }

            // Mutable critical account with no ownership binding
            let is_critical_name = matches!(
                f.name.as_str(),
                "vault" | "pool" | "config" | "treasury" | "state" | "reserve"
            );
            if f.is_mut && !f.is_signer && !f.has_has_one && !f.has_constraint
                && f.seeds.is_empty() && is_critical_name
                && !f.field_type.contains("Program <")
                && !f.field_type.contains("Sysvar <")
            {
                let (snippet, line) = visitor.snippet_for_pattern(
                    &s.file, &format!("pub {}", f.name), 3,
                );
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::Medium,
                    category: Category::AccountValidation,
                    title: format!("Mutable `{}` has no ownership constraint", f.name),
                    file: s.file.clone(), line: Some(line),
                    function: s.name.clone(),
                    snippet,
                    description: format!(
                        "Field `{}` in `{}` is `#[account(mut)]` but has no `has_one`, `constraint`, \
                        or PDA seeds. Any account with the matching discriminator can be substituted — \
                        a type cosplay or account substitution attack may be possible.",
                        f.name, s.name
                    ),
                    recommendation: "Bind this account to a verified authority with `has_one = authority` \
                        or use PDA seeds that include the authority's pubkey so only the legitimate \
                        owner can derive it.".into(),
                    anchor_fix: "#[account(mut, has_one = authority @ ErrorCode::InvalidOwner)]".into(),
                    cwe: "CWE-284".into(),
                    needs_ai_context: true, // needs AI to check whether business logic protects it
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }
        }
    }

    // Unchecked program account (arbitrary CPI)
    for file in files {
        if !file.path.ends_with(".rs") { continue; }
        for (i, line) in file.content.lines().enumerate() {
            let t = line.trim();
            if t.contains(": AccountInfo") && t.contains("program")
                && !t.contains("system_program") && !t.contains("token_program")
                && !t.contains("associated_token") && !t.contains("metadata_program")
                && t.starts_with("pub ")
            {
                let snippet = get_line_snippet(&file.content, i, 2);
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::High,
                    category: Category::AccountValidation,
                    title: "Unchecked program account — arbitrary CPI attack possible".into(),
                    file: file.path.clone(), line: Some(i + 1),
                    function: String::new(),
                    snippet,
                    description: "A program account typed as `AccountInfo<'info>` performs no \
                        verification that the passed account is the expected program. An attacker \
                        can supply their own malicious program, hijacking any CPI made through it.".into(),
                    recommendation: "Use `Program<'info, Token>` or `Interface<'info, TokenInterface>` \
                        to enforce program ID checks automatically. Never accept a program account \
                        as raw AccountInfo.".into(),
                    anchor_fix: "pub token_program: Program<'info, Token>".into(),
                    cwe: "CWE-345".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }
        }
    }

    out
}

//   2. ARITHMETIC OVERFLOW                          ─

fn check_arithmetic(
    visitor: &ProjectVisitor,
    files: &[InputFile],
    next_id: &mut impl FnMut() -> String,
) -> Vec<Finding> {
    let mut out = vec![];
    let safe = visitor.overflow_checks_enabled;

    for op in &visitor.arithmetic_ops {
        if op.uses_checked { continue; }

        match op.op.as_str() {
            "/" => {
                let (snippet, line) = visitor.snippet_for_pattern(
                    &op.file, &op.in_function, 2,
                );
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::Medium,
                    category: Category::ArithmeticOverflow,
                    title: format!("Integer division in `{}` truncates precision", op.in_function),
                    file: op.file.clone(), line: Some(line),
                    function: op.in_function.clone(),
                    snippet,
                    description: "Integer division truncates towards zero. In AMM calculations \
                        (e.g. `reserve_b * amount_in / reserve_a`), dividing before multiplying \
                        permanently loses precision. This enables dust-amount manipulation attacks \
                        where tiny inputs extract disproportionate outputs.".into(),
                    recommendation: "Multiply before dividing. Use u128 for intermediates: \
                        `((a as u128) * (b as u128) / (c as u128)) as u64`.".into(),
                    anchor_fix: String::new(),
                    cwe: "CWE-682".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }
            "+" | "-" if !safe => {
                let (snippet, line) = visitor.snippet_for_pattern(
                    &op.file, &op.in_function, 2,
                );
                let method = if op.op == "+" { "checked_add" } else { "checked_sub" };
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::High,
                    category: Category::ArithmeticOverflow,
                    title: format!("Unchecked `{}` on token amount in `{}`", op.op, op.in_function),
                    file: op.file.clone(), line: Some(line),
                    function: op.in_function.clone(),
                    snippet,
                    description: format!(
                        "Unchecked `{}` on a u64 amount in `{}` with no `overflow-checks = true` \
                        in Cargo.toml. In release builds, Rust u64 wraps silently — an overflow \
                        on a balance can produce u64::MAX after subtraction, or near-zero after addition.",
                        op.op, op.in_function
                    ),
                    recommendation: format!(
                        "Replace `a {} b` with `a.{}(b).ok_or(ErrorCode::Overflow)?` \
                        or add `overflow-checks = true` under `[profile.release]` in Cargo.toml.",
                        op.op, method
                    ),
                    anchor_fix: String::new(),
                    cwe: "CWE-190".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }
            "*" if !safe => {
                let (snippet, line) = visitor.snippet_for_pattern(
                    &op.file, &op.in_function, 2,
                );
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::High,
                    category: Category::ArithmeticOverflow,
                    title: format!("Unchecked multiplication on token amount in `{}`", op.in_function),
                    file: op.file.clone(), line: Some(line),
                    function: op.in_function.clone(),
                    snippet,
                    description: format!(
                        "Unchecked `*` on u64 in `{}`. Two u64 values can easily exceed u64::MAX \
                        (18.4e18) — reward_rate * staked_amount, or fee_bps * amount, overflow at \
                        modest values. Without overflow-checks, the result wraps silently.",
                        op.in_function
                    ),
                    recommendation: "Use checked_mul or cast to u128: \
                        `((a as u128).checked_mul(b as u128).ok_or(ErrorCode::Overflow)?) as u64`.".into(),
                    anchor_fix: String::new(),
                    cwe: "CWE-190".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }
            _ => {}
        }
    }

    // Slippage check absence
    for file in files {
        if !file.path.ends_with(".rs") { continue; }
        let content = &file.content;
        let lower = content.to_lowercase();
        let has_swap = lower.contains("amount_out") || lower.contains("swap");
        let has_slippage = (lower.contains("min_out") || lower.contains("minimum_amount"))
            && lower.contains("require!");
        if has_swap && !has_slippage {
            for (i, line) in content.lines().enumerate() {
                if line.contains("amount_out") && !line.trim_start().starts_with("//") {
                    let snippet = get_line_snippet(content, i, 3);
                    out.push(Finding {
                        id: next_id(),
                        severity: Severity::High,
                        category: Category::ArithmeticOverflow,
                        title: "Slippage protection missing — min_out not enforced".into(),
                        file: file.path.clone(), line: Some(i + 1),
                        function: String::new(),
                        snippet,
                        description: "`amount_out` is computed but never validated against a \
                            caller-supplied minimum. An attacker can sandwich this transaction: \
                            front-run to move price, let the victim swap at a worse rate, back-run.".into(),
                        recommendation: "Add `require!(amount_out >= min_out, ErrorCode::SlippageExceeded)` \
                            immediately after computing amount_out.".into(),
                        anchor_fix: "require!(amount_out >= min_out, ErrorCode::SlippageExceeded)".into(),
                        cwe: "CWE-682".into(),
                        needs_ai_context: false,
                        ai_explanation: None,
                        ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                    });
                    break;
                }
            }
        }
    }

    out
}

//   3. SIGNER AUTHORITY                            ─

fn check_signer_authority(
    visitor: &ProjectVisitor,
    files: &[InputFile],
    next_id: &mut impl FnMut() -> String,
) -> Vec<Finding> {
    let mut out = vec![];

    for s in &visitor.account_structs {
        for f in &s.fields {
            let is_authority_name = matches!(
                f.name.as_str(),
                "authority" | "admin" | "maker" | "owner" | "operator" | "creator" | "payer"
            );
            let is_raw_ai = f.field_type.contains("AccountInfo")
                && !f.field_type.contains("Program <")
                && !f.field_type.contains("Sysvar <");
            let is_system_account = f.field_type.contains("SystemAccount");

            if is_authority_name && (is_raw_ai || is_system_account) && !f.is_signer {
                let sev = if is_raw_ai { Severity::Critical } else { Severity::High };
                let type_name = if is_raw_ai { "AccountInfo" } else { "SystemAccount" };
                let (snippet, line) = visitor.snippet_for_pattern(
                    &s.file, &format!("pub {}", f.name), 4,
                );
                out.push(Finding {
                    id: next_id(),
                    severity: sev,
                    category: Category::SignerAuthority,
                    title: format!(
                        "Authority `{}` is `{}` — transaction signature never verified",
                        f.name, type_name
                    ),
                    file: s.file.clone(), line: Some(line),
                    function: s.name.clone(),
                    snippet,
                    description: format!(
                        "`{}` in `{}` is typed as `{}<'info>`. {} \
                        An attacker only needs to know the authority pubkey — no private key required.",
                        f.name, s.name, type_name,
                        if is_raw_ai {
                            "AccountInfo performs zero checks — no ownership, no signature."
                        } else {
                            "SystemAccount verifies System Program ownership but does NOT require a signature."
                        }
                    ),
                    recommendation: format!(
                        "Change to `pub {}: Signer<'info>`. Anchor's Signer<> type automatically \
                        verifies the account signed this transaction. Pair with `has_one = {}` on \
                        any state account that stores this authority.",
                        f.name, f.name
                    ),
                    anchor_fix: format!("pub {}: Signer<'info>", f.name),
                    cwe: "CWE-862".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }
        }
    }

    // Scan for admin mutation with AccountInfo authority in source
    for file in files {
        if !file.path.ends_with(".rs") { continue; }
        let content = &file.content;
        let lines: Vec<&str> = content.lines().collect();

        for (i, &line) in lines.iter().enumerate() {
            let t = line.trim();
            if (t.contains("pub authority: AccountInfo") || t.contains("pub admin: AccountInfo"))
                && !t.contains("//")
            {
                let ctx_start = i.saturating_sub(5);
                let ctx_end = (i + 15).min(lines.len());
                let ctx_str = lines[ctx_start..ctx_end].join("\n");

                let is_admin_ctx = ctx_str.contains("fee_bps") || ctx_str.contains("reward_rate")
                    || ctx_str.contains("paused") || ctx_str.contains("config")
                    || ctx_str.contains("update") || ctx_str.contains("set_");

                if is_admin_ctx {
                    let snippet = get_line_snippet(content, i, 5);
                    out.push(Finding {
                        id: next_id(),
                        severity: Severity::Critical,
                        category: Category::SignerAuthority,
                        title: "Admin instruction accepts AccountInfo — signature never required".into(),
                        file: file.path.clone(), line: Some(i + 1),
                        function: String::new(),
                        snippet,
                        description: "An admin/config-mutating context has `authority` or `admin` \
                            as `AccountInfo<'info>`. AccountInfo enforces nothing. Any transaction \
                            can pass any pubkey as authority and mutate critical program parameters \
                            (fees, rates, pause state) without possessing the authority's private key.".into(),
                        recommendation: "Replace `AccountInfo<'info>` with `Signer<'info>` for all \
                            authority accounts in admin instructions. Add `has_one = authority` or \
                            `constraint = authority.key() == config.authority`.".into(),
                        anchor_fix: "pub authority: Signer<'info>".into(),
                        cwe: "CWE-862".into(),
                        needs_ai_context: false,
                        ai_explanation: None,
                        ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                    });
                    break;
                }
            }
        }
    }

    out
}

//   4. PDA SEED COLLISION                           ─

fn check_pda_seeds(
    visitor: &ProjectVisitor,
    _files: &[InputFile],
    next_id: &mut impl FnMut() -> String,
) -> Vec<Finding> {
    let mut out = vec![];

    for pda in &visitor.pda_derivations {
        // Bump not stored → canonical bump not enforced on reuse
        if !pda.bump_stored {
            let (snippet, line) = visitor.snippet_for_pattern(
                &pda.file, &pda.account_name, 3,
            );
            out.push(Finding {
                id: next_id(),
                severity: Severity::High,
                category: Category::PdaSeedCollision,
                title: format!("PDA `{}` bump not stored — canonical bump unenforceable on reuse", pda.account_name),
                file: pda.file.clone(), line: Some(line),
                function: pda.account_name.clone(),
                snippet,
                description: format!(
                    "PDA `{}` uses `bump` during init but doesn't store the canonical bump in the \
                    account struct. On subsequent instructions, Anchor can't use `bump = account.bump` — \
                    it must search all 256 values, and if a non-canonical bump is supplied by a caller, \
                    a different PDA address may be derived.",
                    pda.account_name
                ),
                recommendation: format!(
                    "Add `pub bump: u8` to the `{}` state struct. On init: \
                    `account.bump = ctx.bumps.{};`. On every subsequent use: \
                    `#[account(seeds = [...], bump = {}.bump)]`.",
                    pda.account_name, pda.account_name, pda.account_name
                ),
                anchor_fix: format!("bump = {}.bump", pda.account_name),
                cwe: "CWE-330".into(),
                needs_ai_context: false,
                ai_explanation: None,
                ai_severity: None,
exploitability: 0,
                confirmed_by_taint: vec![],
            });
        }

        // Seeds without unique per-user discriminator → collision between users
        let has_unique = pda.seeds.iter().any(|s| {
            s.contains("key()") || s.contains("mint") || s.contains("user")
                || s.contains("maker") || s.contains("owner") || s.contains("seed")
                || s.contains("to_le_bytes")
        });

        if !has_unique && pda.seeds.len() <= 1 {
            let (snippet, line) = visitor.snippet_for_pattern(
                &pda.file, "seeds = [", 3,
            );
            out.push(Finding {
                id: next_id(),
                severity: Severity::Medium,
                category: Category::PdaSeedCollision,
                title: format!("PDA `{}` seeds lack unique per-user discriminator", pda.account_name),
                file: pda.file.clone(), line: Some(line),
                function: pda.account_name.clone(),
                snippet,
                description: format!(
                    "PDA `{}` uses seeds {:?} — static seeds shared across all users. If multiple \
                    users interact with this program, all derive the same PDA address. The first \
                    to call init owns the account; all others will interact with that same account.",
                    pda.account_name, pda.seeds
                ),
                recommendation: "Include a unique discriminator: the user's pubkey, a mint address, \
                    or a user-supplied u64 seed. Example: \
                    `seeds = [b\"vault\", authority.key().as_ref()]`".into(),
                anchor_fix: format!(
                    "seeds = [b\"{}\", authority.key().as_ref()]",
                    pda.account_name.to_lowercase()
                ),
                cwe: "CWE-330".into(),
                needs_ai_context: true,
                ai_explanation: None,
                ai_severity: None,
exploitability: 0,
                confirmed_by_taint: vec![],
            });
        }
    }

    out
}

//   5. REENTRANCY                               ─

fn check_reentrancy(
    visitor: &ProjectVisitor,
    files: &[InputFile],
    next_id: &mut impl FnMut() -> String,
) -> Vec<Finding> {
    let mut out = vec![];

    for file in files {
        if !file.path.ends_with(".rs") { continue; }
        let content = &file.content;
        let lines: Vec<&str> = content.lines().collect();

        let mut current_fn = String::new();
        let mut fn_had_cpi = false;
        let mut cpi_line_idx: Option<usize> = None;

        for (i, &line) in lines.iter().enumerate() {
            let t = line.trim();

            // Track function boundaries
            if t.starts_with("pub fn ") || t.starts_with("fn ") {
                current_fn = t.split('(').next().unwrap_or("")
                    .split_whitespace().last().unwrap_or("").to_string();
                fn_had_cpi = false;
                cpi_line_idx = None;
            }

            let is_cpi = t.contains("transfer(") || t.contains("transfer_checked(")
                || t.contains("invoke(") || t.contains("invoke_signed(")
                || t.contains("close_account(");

            if is_cpi {
                fn_had_cpi = true;
                if cpi_line_idx.is_none() { cpi_line_idx = Some(i); }
            }

            // Stale vault.amount read AFTER a CPI
            if fn_had_cpi && (t.contains("self.vault.amount") || t.contains(".vault.amount")) {
                let snippet = get_line_snippet(content, i, 5);
                out.push(Finding {
                    id: next_id(),
                    severity: Severity::High,
                    category: Category::Reentrancy,
                    title: format!("Stale `vault.amount` read after CPI in `{}`", current_fn),
                    file: file.path.clone(), line: Some(i + 1),
                    function: current_fn.clone(),
                    snippet,
                    description: format!(
                        "In `{}`, `self.vault.amount` is read to determine transfer amount AFTER \
                        a prior CPI has already executed. With Token-2022 transfer hooks, the \
                        intermediate CPI can modify vault state, making the cached amount stale. \
                        This can transfer more or fewer tokens than intended.",
                        current_fn
                    ),
                    recommendation: "Cache the vault amount before ANY CPI: \
                        `let vault_amount = self.vault.amount;` at the top of the function. \
                        Or call `self.vault.reload()?` after each CPI before reading amounts.".into(),
                    anchor_fix: "let vault_amount = self.vault.amount; // before any CPI".into(),
                    cwe: "CWE-362".into(),
                    needs_ai_context: false,
                    ai_explanation: None,
                    ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                });
            }

            // State mutation AFTER CPI (checks-effects-interactions violation)
            if let Some(cpi_i) = cpi_line_idx {
                if i > cpi_i + 1 {
                    let is_state_write = (t.contains(".total_") || t.contains(".balance")
                        || t.contains(".amount") || t.contains(".reserve")
                        || t.contains(".staked") || t.contains(".supply"))
                        && (t.contains("+=") || t.contains("-=")
                            || (t.contains('=') && !t.contains("==") && !t.starts_with("let ")));

                    if is_state_write {
                        let snippet = get_line_snippet(content, i, 6);
                        out.push(Finding {
                            id: next_id(),
                            severity: Severity::Medium,
                            category: Category::Reentrancy,
                            title: format!(
                                "State mutation after CPI in `{}` — checks-effects-interactions violated",
                                current_fn
                            ),
                            file: file.path.clone(), line: Some(i + 1),
                            function: current_fn.clone(),
                            snippet,
                            description: format!(
                                "In `{}`, program state (balance/amount/reserve field) is mutated \
                                AFTER a CPI call. This violates checks-effects-interactions. With \
                                Token-2022 transfer hooks, the external call can observe or modify \
                                state mid-execution before your mutation applies.",
                                current_fn
                            ),
                            recommendation: "Move all state mutations BEFORE CPI calls. \
                                Update balances and counters first, then perform external calls. \
                                This matches the checks-effects-interactions pattern.".into(),
                            anchor_fix: String::new(),
                            cwe: "CWE-362".into(),
                            needs_ai_context: true,
                            ai_explanation: None,
                            ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                        });
                        cpi_line_idx = None; // one finding per CPI block
                    }
                }
            }
        }
    }

    // CPI ordering in lib.rs: deposit() before withdraw_and_close_vault()
    // deposit CPI fires first → Token-2022 hook can re-enter
    for file in files {
        if !file.path.ends_with(".rs") { continue; }
        let content = &file.content;
        for (i, line) in content.lines().enumerate() {
            let t = line.trim();
            if t.contains("deposit()") || t.contains("deposit()?") {
                // Look for withdraw/close within 3 lines after
                let rest: Vec<&str> = content.lines().skip(i + 1).take(3).collect();
                let has_withdraw = rest.iter().any(|l| {
                    l.contains("withdraw") || l.contains("close_vault")
                });
                if has_withdraw {
                    let snippet = get_line_snippet(content, i, 3);
                    out.push(Finding {
                        id: next_id(),
                        severity: Severity::Medium,
                        category: Category::Reentrancy,
                        title: "CPI ordering: deposit fires before withdraw — Token-2022 hook re-entry risk".into(),
                        file: file.path.clone(), line: Some(i + 1),
                        function: String::new(),
                        snippet,
                        description: "deposit() (taker pays maker) is called BEFORE withdraw_and_close_vault() \
                            (vault pays taker). With Token-2022 transfer hooks, the deposit CPI can invoke \
                            arbitrary logic. If that logic re-enters this program (e.g. via a second take), \
                            the vault still holds its tokens and can be drained.".into(),
                        recommendation: "Reorder: call withdraw_and_close_vault() first to drain/close the vault, \
                            then call deposit() to collect payment. Vault is empty before any external CPI.".into(),
                        anchor_fix: String::new(),
                        cwe: "CWE-362".into(),
                        needs_ai_context: true,
                        ai_explanation: None,
                        ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                    });
                }
            }
        }
    }

    out
}

//   6. ACCESS CONTROL                             ─

fn check_access_control(
    visitor: &ProjectVisitor,
    files: &[InputFile],
    next_id: &mut impl FnMut() -> String,
) -> Vec<Finding> {
    let mut out = vec![];

    for s in &visitor.account_structs {
        // Find instruction using this Accounts struct
        let instr_name = visitor.instructions.iter()
            .find(|i| i.ctx_type == s.name)
            .map(|i| i.name.clone())
            .unwrap_or_else(|| s.name.to_lowercase());

        let is_admin_fn = instr_name.contains("update") || instr_name.contains("set_")
            || instr_name.contains("change") || instr_name.contains("configure")
            || instr_name.contains("admin") || instr_name.contains("pause")
            || instr_name.contains("upgrade") || instr_name.contains("initialize");

        if is_admin_fn && !s.has_signer {
            let (snippet, line) = visitor.snippet_for_pattern(&s.file, &s.name, 6);
            out.push(Finding {
                id: next_id(),
                severity: Severity::Critical,
                category: Category::AccessControl,
                title: format!("Admin instruction `{}` has no Signer — callable by anyone", instr_name),
                file: s.file.clone(), line: Some(line),
                function: instr_name.clone(),
                snippet,
                description: format!(
                    "Instruction `{}` (using struct `{}`) contains no `Signer<'info>` typed account. \
                    Any transaction can call this instruction. Admin-only operations like fee updates, \
                    rate changes, and pausing have no access control whatsoever.",
                    instr_name, s.name
                ),
                recommendation: format!(
                    "Add `pub authority: Signer<'info>` to `{}`. \
                    Link it to stored admin: `has_one = authority @ ErrorCode::Unauthorized` \
                    on the config/state account.",
                    s.name
                ),
                anchor_fix: "pub authority: Signer<'info>".into(),
                cwe: "CWE-862".into(),
                needs_ai_context: false,
                ai_explanation: None,
                ai_severity: None,
exploitability: 0,
                confirmed_by_taint: vec![],
            });
        }
    }

    // Zero-amount check absence
    for file in files {
        if !file.path.ends_with(".rs") { continue; }
        let content = &file.content;
        for (i, line) in content.lines().enumerate() {
            let t = line.trim();
            if t.starts_with("pub fn ")
                && (t.contains("deposit") || t.contains("stake") || t.contains("make"))
            {
                let body: String = content.lines().skip(i).take(25).collect::<Vec<_>>().join("\n");
                let has_amount = body.contains("amount: u64") || body.contains("deposit: u64");
                let has_check = body.contains("require!") && body.contains("> 0");

                if has_amount && !has_check {
                    let snippet = get_line_snippet(content, i, 2);
                    out.push(Finding {
                        id: next_id(),
                        severity: Severity::Medium,
                        category: Category::AccessControl,
                        title: format!(
                            "No zero-amount validation in `{}` — griefing attack surface",
                            t.split('(').next().unwrap_or("").trim()
                        ),
                        file: file.path.clone(), line: Some(i + 1),
                        function: t.split('(').next().unwrap_or("").trim().to_string(),
                        snippet,
                        description: "This instruction accepts a u64 amount parameter with no \
                            zero-value check. An attacker can spam zero-value calls to bloat \
                            event logs, waste compute, or create zero-balance PDAs consuming rent.".into(),
                        recommendation: "Add at the top of the handler body: \
                            `require!(amount > 0, ErrorCode::ZeroAmount);`".into(),
                        anchor_fix: "require!(amount > 0, ErrorCode::ZeroAmount)".into(),
                        cwe: "CWE-20".into(),
                        needs_ai_context: false,
                        ai_explanation: None,
                        ai_severity: None,
                    exploitability: 0,
                    confirmed_by_taint: vec![],
                    });
                    break;
                }
            }
        }
    }

    out
}
