// backend/src/pdf.rs
// Generate PDF reports - simplified version

use crate::types::AnalysisReport;
use printpdf::*;
use std::fs::File;
use std::io::BufWriter;

pub fn generate_pdf(report: &AnalysisReport, path: &str) -> std::io::Result<()> {
    let (doc, page1, layer1) = PdfDocument::new(
        &format!("ChainProbe Report - {}", report.profile.program_name),
        Mm(210.0),
        Mm(297.0),
        "Layer 1",
    );

    let font = doc.add_builtin_font(BuiltinFont::Helvetica).unwrap();
    let font_bold = doc.add_builtin_font(BuiltinFont::HelveticaBold).unwrap();

    let current_layer = doc.get_page(page1).get_layer(layer1);
    
    let y = 270.0;
    current_layer.use_text("ChainProbe Security Audit", 20.0, Mm(20.0), Mm(y), &font_bold);
    current_layer.use_text(&report.profile.program_name, 14.0, Mm(20.0), Mm(y - 12.0), &font);
    
    let summary = &report.summary;
    let y = 240.0;
    current_layer.use_text(&format!("Security Score: {}", summary.security_score), 12.0, Mm(20.0), Mm(y), &font_bold);
    current_layer.use_text(&format!("Risk Level: {}", summary.overall_risk), 12.0, Mm(20.0), Mm(y - 8.0), &font);
    current_layer.use_text(&format!("Critical: {} | High: {} | Medium: {} | Low: {}", 
        summary.critical, summary.high, summary.medium, summary.low), 11.0, Mm(20.0), Mm(y - 18.0), &font);
    current_layer.use_text(&format!("Files: {} | Lines: {}", report.profile.files_analyzed, report.profile.total_lines), 11.0, Mm(20.0), Mm(y - 28.0), &font);
    current_layer.use_text(&format!("Vulnerability Chains: {}", summary.chain_count), 11.0, Mm(20.0), Mm(y - 38.0), &font);
    
    // Footer
    current_layer.use_text(
        &format!("Generated by ChainProbe v4 | {}", chrono::Utc::now().format("%Y-%m-%d")),
        8.0,
        Mm(20.0),
        Mm(10.0),
        &font,
    );
    
    let file = File::create(path).map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;
    doc.save(&mut BufWriter::new(file)).map_err(|e| std::io::Error::new(std::io::ErrorKind::Other, e))?;
    Ok(())
}